# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=siget
      - POSTGRES_PASSWORD=siget
      - POSTGRES_DB=siget
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: