import { PrismaClient, TipoEmpresa, NivelSoporte, Prioridad } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log(`Start seeding ...`);

  // --- Limpiar datos existentes (en orden de dependencia) ---
  console.log('Cleaning existing data...');
  await prisma.notificacionesCorreo.deleteMany({});
  await prisma.historialSolicitud.deleteMany({});
  await prisma.traslado.deleteMany({});
  await prisma.ticket.deleteMany({});
  await prisma.asignacionesCategorias.deleteMany({});
  await prisma.subcategoriaCategorias.deleteMany({});
  await prisma.subcategoria.deleteMany({});
  await prisma.categoria.deleteMany({});
  await prisma.logs.deleteMany({});
  await prisma.usuario.deleteMany({});
  await prisma.rol.deleteMany({});
  await prisma.bloque.deleteMany({});
  await prisma.ciclo.deleteMany({});
  await prisma.carrera.deleteMany({});
  await prisma.oferta.deleteMany({});
  await prisma.descuento.deleteMany({});
  await prisma.planPago.deleteMany({});
  await prisma.empresa.deleteMany({});
  await prisma.estatus.deleteMany({});
  
  // --- Insertar Empresas ---
  console.log('Seeding empresa...');
  await prisma.empresa.createMany({
    data: [
      { id: 1, nombre: 'Cancún', slug: 'cancun', tipo: 'Magno' },
      { id: 2, nombre: 'Chihuahua', slug: 'chihuahua', tipo: 'Magno' },
      { id: 3, nombre: 'Cuernavaca', slug: 'cuernavaca', tipo: 'Social' },
      { id: 4, nombre: 'Del Valle', slug: 'del-valle', tipo: 'Magno' },
      { id: 5, nombre: 'Guadalajara', slug: 'guadalajara', tipo: 'Ejecutivo' },
      { id: 6, nombre: 'Mérida', slug: 'merida', tipo: 'Magno' },
      { id: 7, nombre: 'Monterrey', slug: 'monterrey', tipo: 'Ejecutivo' },
      { id: 8, nombre: 'Presa Madín', slug: 'presa-madin', tipo: 'Magno' },
      { id: 9, nombre: 'Querétaro', slug: 'queretaro', tipo: 'Magno' },
      { id: 10, nombre: 'Reyes', slug: 'reyes', tipo: 'Magno' },
      { id: 11, nombre: 'Santa Fe', slug: 'santa-fe', tipo: 'Ejecutivo' },
      { id: 12, nombre: 'Tijuana', slug: 'tijuana', tipo: 'Magno' },
      { id: 13, nombre: 'Virtual', slug: 'virtual', tipo: 'Ejecutivo' },
      { id: 14, nombre: 'Corporativo', slug: 'corporativo', tipo: 'Oficina' },
      { id: 15, nombre: 'CSH', slug: 'csh', tipo: 'Oficina' },
    ],
  });

  // --- Insertar Roles ---
  console.log('Seeding rol...');
  await prisma.rol.createMany({
    data: [
      { id: 1, rol: 'Director CSH', descripcion: 'Director del Centro de Soporte', nivel_soporte: 'S_3' },
      { id: 2, rol: 'Ingeniero soporte 1', descripcion: 'Ingeniero de soporte nivel 1', nivel_soporte: 'S_1' },
      { id: 3, rol: 'Ingeniero soporte 2', descripcion: 'Ingeniero de soporte nivel 2', nivel_soporte: 'S_2' },
      { id: 4, rol: 'Ingeniero soporte 3', descripcion: 'Ingeniero de soporte nivel 3', nivel_soporte: 'S_3' },
      { id: 5, rol: 'Auditor CSH', descripcion: 'Auditor del centro de soporte', nivel_soporte: 'S_1' },
      { id: 6, rol: 'Desarrollador', descripcion: 'Desarrollador de aplicaciones', nivel_soporte: 'Desarrollador' },
      { id: 7, rol: 'Director campus', descripcion: 'Director de campus', nivel_soporte: 'S_1' },
      { id: 8, rol: 'Coordinador RR.PP.', descripcion: 'Coordinador de relaciones públicas', nivel_soporte: 'S_1' },
      { id: 9, rol: 'Ejecutivo RR.PP.', descripcion: 'Ejecutivo de relaciones públicas', nivel_soporte: 'S_1' },
      { id: 10, rol: 'Contador', descripcion: 'Contador', nivel_soporte: 'Contador' },
      { id: 11, rol: 'Director Marketing', descripcion: 'Director de Marketing', nivel_soporte: 'Marketing' },
      { id: 12, rol: 'Diseñador', descripcion: 'Diseñador gráfico (Marketing)', nivel_soporte: 'Marketing' },
      { id: 13, rol: 'Community manager', descripcion: 'Ejecutivo de atención en redes sociales', nivel_soporte: 'Marketing' },
      { id: 14, rol: 'Visitante', descripcion: 'Visitante', nivel_soporte: 'S_1' },
      { id: 15, rol: 'Visitante administrador', descripcion: 'Visitante administrador', nivel_soporte: 'S_1' },
    ],
  });

  // --- Insertar Oferta ---
  console.log('Seeding oferta...');
  await prisma.oferta.createMany({
    data: [
        { id: 1, descripcion: 'Licenciatura Ejecutiva' },
        { id: 2, descripcion: 'Licenciatura Escolarizada' },
        { id: 3, descripcion: 'Maestría' },
        { id: 4, descripcion: 'Doctorado' },
        { id: 5, descripcion: 'Diplomado' },
        { id: 6, descripcion: 'Idioma' },
    ],
  });

  // --- Insertar Descuento ---
  console.log('Seeding descuento...');
  await prisma.descuento.createMany({
    data: [
        { id: 13, descripcion: 'Beca 50', monto: 50, activo: true },
        { id: 14, descripcion: 'Beca Colab.', monto: 100, activo: true },
        { id: 15, descripcion: 'Convenio', monto: 10, activo: true },
        { id: 16, descripcion: 'Desc.Esp.', monto: 0, activo: true },
    ],
  });

  // --- Insertar Estatus ---
  console.log('Seeding estatus...');
  await prisma.estatus.createMany({
    data: [
        { id: 1, nombre: 'Sin asignar', descripcion: 'Ticket nuevo sin agente asignado.' },
        { id: 2, nombre: 'Nuevo', descripcion: 'Ticket nuevo en el sistema y asignado' },
        { id: 3, nombre: 'En progreso', descripcion: 'El ticket está siendo atendido por un ingeniero de soporte.' },
        { id: 4, nombre: 'En espera', descripcion: 'El ticket está siendo atendido' },
        { id: 5, nombre: 'Solucionado', descripcion: 'Ticket cerrado' },
        { id: 6, nombre: 'Cancelado', descripcion: 'Ticket cancelado' },
        { id: 7, nombre: 'Duplicado', descripcion: 'Solicitud duplicada' },
        { id: 8, nombre: 'Revisión CSH', descripcion: 'Traslado: Revisión CSH' },
        { id: 9, nombre: 'Revisión campus origen', descripcion: 'Traslado en revisión por campus origen' },
        { id: 10, nombre: 'Información campus destino', descripcion: 'Traslado en espera de información de campus destino' },
        { id: 11, nombre: 'Confirmación alumno', descripcion: 'Traslado en espera de confirmación del alumno' },
    ],
  });

  // --- Insertar Categoria ---
  console.log('Seeding categoria...');
  await prisma.categoria.createMany({
    data: [
        { id: 1, nombre: 'Alumno', nivel_soporte_requerido: 'S_1', activo: true },
        { id: 2, nombre: 'Aspirante', nivel_soporte_requerido: 'S_1', activo: true },
        { id: 3, nombre: 'Colaborador', nivel_soporte_requerido: 'S_2', activo: true },
        { id: 4, nombre: 'Docente', nivel_soporte_requerido: 'S_2', activo: true },
        { id: 5, nombre: 'Plataforma Humanitas', nivel_soporte_requerido: 'S_2', activo: true },
        { id: 6, nombre: 'App Humanitas', nivel_soporte_requerido: 'S_2', activo: true },
        { id: 7, nombre: 'Canvas', nivel_soporte_requerido: 'S_2', activo: true },
        { id: 8, nombre: 'Hubspot', nivel_soporte_requerido: 'S_2', activo: true },
        { id: 9, nombre: 'Atom', nivel_soporte_requerido: 'S_2', activo: true },
        { id: 10, nombre: 'Página web', nivel_soporte_requerido: 'Desarrollador', activo: true },
        { id: 11, nombre: 'Otro', nivel_soporte_requerido: 'S_1', activo: true },
        { id: 12, nombre: 'Marketing', nivel_soporte_requerido: 'Marketing', activo: true },
    ],
  });

  // --- Insertar Carrera ---
  console.log('Seeding carrera...');
  await prisma.carrera.createMany({
    data: [
        { id: 1, clave: 'LAC', descripcion: 'Administración', ofertaId: 1, activo: true },
        { id: 2, clave: 'LACE', descripcion: 'Administración', ofertaId: 2, activo: true },
        { id: 3, clave: 'LARE', descripcion: 'Arquitectura', ofertaId: 2, activo: true },
        { id: 4, clave: 'LCPAP', descripcion: 'Ciencias Políticas y Administración Pública', ofertaId: 1, activo: true },
        { id: 5, clave: 'LECPA', descripcion: 'Ciencias Políticas y Administración Pública', ofertaId: 2, activo: true },
        { id: 6, clave: 'LAC', descripcion: 'Contabilidad', ofertaId: 1, activo: true },
        { id: 7, clave: 'LACE', descripcion: 'Contabilidad', ofertaId: 2, activo: true },
        { id: 8, clave: 'LD', descripcion: 'Derecho', ofertaId: 1, activo: true },
        { id: 9, clave: 'LDE', descripcion: 'Derecho', ofertaId: 2, activo: true },
        { id: 10, clave: 'LDGE', descripcion: 'Diseño Gráfico', ofertaId: 2, activo: true },
        { id: 11, clave: 'LICED', descripcion: 'Educación', ofertaId: 1, activo: true },
        { id: 12, clave: 'LEED', descripcion: 'Educación', ofertaId: 2, activo: true },
        { id: 13, clave: 'LPS', descripcion: 'Psicología', ofertaId: 1, activo: true },
        { id: 14, clave: 'LPSE', descripcion: 'Psicología', ofertaId: 2, activo: true },
        { id: 15, clave: 'LATE', descripcion: 'Arte y Teatro', ofertaId: 2, activo: true },
        { id: 16, clave: 'MADEE', descripcion: 'Alta Dirección Corporativa', ofertaId: 3, activo: true },
        { id: 17, clave: 'MCEI', descripcion: 'Contabilidad e Impuestos', ofertaId: 3, activo: true },
        { id: 18, clave: 'MDEC', descripcion: 'Derecho Corporativo', ofertaId: 3, activo: true },
        { id: 19, clave: 'MDFI', descripcion: 'Derecho Fiscal', ofertaId: 3, activo: true },
        { id: 20, clave: 'MDP', descripcion: 'Derecho Penal', ofertaId: 3, activo: true },
        { id: 21, clave: 'MAED', descripcion: 'Educación', ofertaId: 3, activo: true },
        { id: 22, clave: 'MJPSP', descripcion: 'Justicia Penal y Seguridad Pública', ofertaId: 3, activo: true },
        { id: 23, clave: 'MMER', descripcion: 'Mercadotecnia', ofertaId: 3, activo: true },
        { id: 24, clave: 'MTPS8', descripcion: 'Psicoterapia con un Enfoque Psicoanalítico', ofertaId: 3, activo: true },
        { id: 25, clave: 'DOCAD', descripcion: 'Alta Dirección', ofertaId: 4, activo: true },
        { id: 26, clave: 'DOCDE', descripcion: 'Derecho', ofertaId: 4, activo: true },
        { id: 27, clave: 'DOCED', descripcion: 'Educación', ofertaId: 4, activo: true },
        { id: 28, clave: 'DIP11', descripcion: 'Diplomado en Bases de Administración y Principios Contables', ofertaId: 5, activo: true },
        { id: 29, clave: 'DIP01', descripcion: 'Diplomado en Criminología', ofertaId: 5, activo: true },
        { id: 30, clave: 'DIP02', descripcion: 'Diplomado en Juicios Orales', ofertaId: 5, activo: true },
        { id: 31, clave: 'DIP09', descripcion: 'Diplomado en Perfiles Criminales', ofertaId: 5, activo: true },
        { id: 32, clave: 'DIP04', descripcion: 'Diplomado en Tanatología', ofertaId: 5, activo: true },
        { id: 33, clave: 'DIP03', descripcion: 'Seminario de Introducción a la Psicoterapia Psicoanalítica en Niños', ofertaId: 5, activo: true },
        { id: 34, clave: 'DIP05', descripcion: 'Seminario de Introducción al Psicoanálisis', ofertaId: 5, activo: true },
        { id: 35, clave: 'DIP06', descripcion: 'Seminario de Reflexiones Psicoanalíticas sobre el Cuerpo, la Anorexia y la Obesidad', ofertaId: 5, activo: true },
        { id: 36, clave: 'ISEMI', descripcion: 'English Kingdom', ofertaId: 6, activo: true },
    ],
  });

  // --- Insertar Subcategorias ---
  console.log('Seeding subcategoria...');
  await prisma.subcategoria.createMany({
    data: [
      { id: 1, nombre: 'Académico', parent_subcategoriaId: null },
      { id: 2, nombre: 'Calificaciones', parent_subcategoriaId: 1 },
      { id: 3, nombre: 'Histórico', parent_subcategoriaId: 2 },
      { id: 4, nombre: 'Kardex', parent_subcategoriaId: 2 },
      { id: 5, nombre: 'Replicar calificaciones', parent_subcategoriaId: 2 },
      { id: 6, nombre: 'Horario', parent_subcategoriaId: 1 },
      { id: 7, nombre: 'Selección de materias', parent_subcategoriaId: 1 },
      { id: 8, nombre: 'Aplicación móvil', parent_subcategoriaId: null },
      { id: 9, nombre: 'Correo institucional', parent_subcategoriaId: null },
      { id: 10, nombre: 'Actualizar', parent_subcategoriaId: 9 },
      { id: 11, nombre: 'Desbloqueo / reactivar', parent_subcategoriaId: 9 },
      { id: 12, nombre: 'Generar correo', parent_subcategoriaId: 9 },
      { id: 13, nombre: 'Redireccionar', parent_subcategoriaId: 9 },
      { id: 14, nombre: 'Restablecer contraseña', parent_subcategoriaId: 9 },
      { id: 15, nombre: 'Datos fiscales', parent_subcategoriaId: null },
      { id: 16, nombre: 'Documentos', parent_subcategoriaId: null },
      { id: 17, nombre: 'Expediente', parent_subcategoriaId: null },
      { id: 18, nombre: 'Nacionalidad', parent_subcategoriaId: 17 },
      { id: 19, nombre: 'Situación', parent_subcategoriaId: 17 },
      { id: 20, nombre: 'Turno', parent_subcategoriaId: 17 },
      { id: 21, nombre: 'Otro', parent_subcategoriaId: 17 },
      { id: 22, nombre: 'Finanzas (estado de cuenta)', parent_subcategoriaId: null },
      { id: 23, nombre: 'Becas', parent_subcategoriaId: 22 },
      { id: 24, nombre: 'Cobros', parent_subcategoriaId: 22 },
      { id: 25, nombre: 'BBVA', parent_subcategoriaId: 24 },
      { id: 26, nombre: 'CoDi', parent_subcategoriaId: 24 },
      { id: 27, nombre: 'En campus', parent_subcategoriaId: 24 },
      { id: 28, nombre: 'TPV (pin pad)', parent_subcategoriaId: 27 },
      { id: 29, nombre: 'Aplicación TPV', parent_subcategoriaId: 27 },
      { id: 30, nombre: 'Flywire', parent_subcategoriaId: 24 },
      { id: 31, nombre: 'PayPal', parent_subcategoriaId: 24 },
      { id: 32, nombre: 'OXXO', parent_subcategoriaId: 24 },
      { id: 33, nombre: 'Descuentos', parent_subcategoriaId: 22 },
      { id: 34, nombre: 'Convenios', parent_subcategoriaId: 33 },
      { id: 35, nombre: 'Inscripción', parent_subcategoriaId: 33 },
      { id: 36, nombre: 'Personales', parent_subcategoriaId: 33 },
      { id: 37, nombre: 'Referidos', parent_subcategoriaId: 33 },
      { id: 38, nombre: 'Retiro de cargos', parent_subcategoriaId: 33 },
      { id: 39, nombre: 'Facturas', parent_subcategoriaId: 22 },
      { id: 40, nombre: 'Notas aclaratorias', parent_subcategoriaId: 22 },
      { id: 41, nombre: 'Plan de pagos', parent_subcategoriaId: 22 },
      { id: 42, nombre: 'Registro de Pagos', parent_subcategoriaId: 22 },
      { id: 43, nombre: 'Colegiatura', parent_subcategoriaId: 42 },
      { id: 44, nombre: 'Ceremonia de graduación', parent_subcategoriaId: 42 },
      { id: 45, nombre: 'Trámites escolares', parent_subcategoriaId: 42 },
      { id: 46, nombre: '4ta. materia', parent_subcategoriaId: 45 },
      { id: 47, nombre: 'Certificado', parent_subcategoriaId: 45 },
      { id: 48, nombre: 'Constancia', parent_subcategoriaId: 45 },
      { id: 49, nombre: 'Credencial', parent_subcategoriaId: 45 },
      { id: 50, nombre: 'Derecho de titulación', parent_subcategoriaId: 45 },
      { id: 51, nombre: 'Dictamen de equivalencias', parent_subcategoriaId: 45 },
      { id: 52, nombre: 'Otros', parent_subcategoriaId: 42 },
      { id: 53, nombre: 'Foto', parent_subcategoriaId: null },
      { id: 54, nombre: 'Historial de estados', parent_subcategoriaId: null },
      { id: 55, nombre: 'Plataforma Humanitas', parent_subcategoriaId: null },
      { id: 56, nombre: 'Restablecer acceso', parent_subcategoriaId: 55 },
      { id: 57, nombre: 'Servicio social', parent_subcategoriaId: null },
      { id: 58, nombre: 'Traslado', parent_subcategoriaId: null },
      { id: 59, nombre: 'Asignación', parent_subcategoriaId: null },
      { id: 60, nombre: 'Estatus asignados', parent_subcategoriaId: null },
      { id: 61, nombre: 'Finanzas', parent_subcategoriaId: null },
      { id: 62, nombre: 'Generar fichas', parent_subcategoriaId: 61 },
      { id: 63, nombre: 'Generar matrícula', parent_subcategoriaId: null },
      { id: 64, nombre: 'Perfil', parent_subcategoriaId: null },
      { id: 65, nombre: 'Actualizar información', parent_subcategoriaId: 64 },
      { id: 66, nombre: 'Altas (nuevo ingreso)', parent_subcategoriaId: null },
      { id: 67, nombre: 'Creación de correo institucional', parent_subcategoriaId: 66 },
      { id: 68, nombre: 'Acceso a plataforma', parent_subcategoriaId: 66 },
      { id: 69, nombre: 'Acceso a Teambook', parent_subcategoriaId: 66 },
      { id: 70, nombre: 'Replicar permisos', parent_subcategoriaId: 66 },
      { id: 71, nombre: 'Bajas', parent_subcategoriaId: null },
      { id: 72, nombre: 'Redireccionar correo institucional', parent_subcategoriaId: 71 },
      { id: 73, nombre: 'Configuración APP TPV', parent_subcategoriaId: null },
      { id: 74, nombre: 'Permisos', parent_subcategoriaId: 55 },
      { id: 75, nombre: 'Teambook', parent_subcategoriaId: null },
      { id: 76, nombre: 'Registro de asistencia', parent_subcategoriaId: 8 },
      { id: 77, nombre: 'Reset de dispositivo', parent_subcategoriaId: 8 },
      { id: 78, nombre: 'Consultas', parent_subcategoriaId: null },
      { id: 79, nombre: 'Grupos', parent_subcategoriaId: null },
      { id: 80, nombre: 'Actividades', parent_subcategoriaId: 79 },
      { id: 81, nombre: 'Cuestionarios', parent_subcategoriaId: 79 },
      { id: 82, nombre: 'Listas', parent_subcategoriaId: 79 },
      { id: 83, nombre: 'Clases', parent_subcategoriaId: 79 },
      { id: 84, nombre: 'Foros', parent_subcategoriaId: 79 },
      { id: 85, nombre: 'Contratos', parent_subcategoriaId: 79 },
      { id: 86, nombre: 'Lista negra', parent_subcategoriaId: null },
      { id: 87, nombre: 'Google Meet: licencia para grabar', parent_subcategoriaId: null },
      { id: 88, nombre: 'Activar descuentos', parent_subcategoriaId: 61 },
      { id: 89, nombre: 'Docentes', parent_subcategoriaId: 23 },
      { id: 90, nombre: 'Colaboradores', parent_subcategoriaId: 23 },
      { id: 91, nombre: 'Actualizar perfil', parent_subcategoriaId: null },
      { id: 92, nombre: 'Correo personal', parent_subcategoriaId: 17 },
      { id: 93, nombre: 'Aprovechamiento', parent_subcategoriaId: 1 },
      { id: 94, nombre: 'Aulas', parent_subcategoriaId: 1 },
      { id: 95, nombre: 'Catálogo de carreras', parent_subcategoriaId: 1 },
      { id: 96, nombre: 'Encuestas', parent_subcategoriaId: 1 },
      { id: 97, nombre: 'Materias', parent_subcategoriaId: 1 },
      { id: 98, nombre: 'Trámites', parent_subcategoriaId: 1 },
      { id: 99, nombre: 'Brindar acceso', parent_subcategoriaId: null },
      { id: 100, nombre: 'Alumno', parent_subcategoriaId: 99 },
      { id: 101, nombre: 'Docente', parent_subcategoriaId: 99 },
      { id: 102, nombre: 'Colaborador', parent_subcategoriaId: 99 },
      { id: 103, nombre: 'Entrega de trabajos', parent_subcategoriaId: null },
      { id: 104, nombre: 'Material faltante', parent_subcategoriaId: null },
      { id: 105, nombre: 'Material incorrecto', parent_subcategoriaId: null },
      { id: 106, nombre: 'Plataforma caída', parent_subcategoriaId: null },
      { id: 107, nombre: 'Visualización de contenido', parent_subcategoriaId: null },
      { id: 108, nombre: 'Altas', parent_subcategoriaId: null },
      { id: 109, nombre: 'RRPP', parent_subcategoriaId: 108 },
      { id: 110, nombre: 'Marketing', parent_subcategoriaId: 108 },
      { id: 111, nombre: 'Otro perfil', parent_subcategoriaId: 108 },
      { id: 112, nombre: 'Cookies', parent_subcategoriaId: null },
      { id: 113, nombre: 'Dashboards', parent_subcategoriaId: null },
      { id: 114, nombre: 'Dominios', parent_subcategoriaId: null },
      { id: 115, nombre: 'Landing', parent_subcategoriaId: null },
      { id: 116, nombre: 'Diseño', parent_subcategoriaId: 115 },
      { id: 117, nombre: 'Formularios', parent_subcategoriaId: 115 },
      { id: 118, nombre: 'Leads', parent_subcategoriaId: null },
      { id: 119, nombre: 'Mailing', parent_subcategoriaId: null },
      { id: 120, nombre: 'Negocios (comprador)', parent_subcategoriaId: null },
      { id: 121, nombre: 'Alta', parent_subcategoriaId: null },
      { id: 122, nombre: 'Usuarios', parent_subcategoriaId: 121 },
      { id: 123, nombre: 'Plantilla', parent_subcategoriaId: 121 },
      { id: 124, nombre: 'Actualización', parent_subcategoriaId: null },
      { id: 125, nombre: 'Flujo', parent_subcategoriaId: null },
      { id: 126, nombre: 'Bot', parent_subcategoriaId: null },
      { id: 127, nombre: 'Formulario de contacto', parent_subcategoriaId: null },
      { id: 128, nombre: 'Página caída', parent_subcategoriaId: null },
      { id: 129, nombre: 'Diseño', parent_subcategoriaId: null },
      { id: 130, nombre: 'Diseño de postal', parent_subcategoriaId: 129 },
      { id: 131, nombre: 'Mailings', parent_subcategoriaId: 129 },
      { id: 132, nombre: 'Convenios', parent_subcategoriaId: 129 },
      { id: 133, nombre: 'Archivos y materiales para impresión', parent_subcategoriaId: 129 },
      { id: 134, nombre: 'Firmas', parent_subcategoriaId: 129 },
      { id: 135, nombre: 'Señalética institucional', parent_subcategoriaId: 129 },
      { id: 136, nombre: 'Proyectos especiales', parent_subcategoriaId: 129 },
      { id: 137, nombre: 'Botargas', parent_subcategoriaId: 129 },
      { id: 138, nombre: 'Redes sociales', parent_subcategoriaId: null },
      { id: 139, nombre: 'Publicación para redes sociales', parent_subcategoriaId: 138 },
      { id: 140, nombre: 'Publicación de colaboradores', parent_subcategoriaId: 138 },
      { id: 141, nombre: 'Video', parent_subcategoriaId: null },
      { id: 142, nombre: 'Video institucional', parent_subcategoriaId: 141 },
    ],
  });

  // --- Insertar SubcategoriaCategorias ---
  console.log('Seeding subcategoria_categorias...');
  await prisma.subcategoriaCategorias.createMany({
    data: [
      { categoriaId: 1, subcategoriaId: 1 },
      { categoriaId: 1, subcategoriaId: 2 },
      { categoriaId: 1, subcategoriaId: 3 },
      { categoriaId: 1, subcategoriaId: 4 },
      { categoriaId: 1, subcategoriaId: 5 },
      { categoriaId: 1, subcategoriaId: 6 },
      { categoriaId: 1, subcategoriaId: 7 },
      { categoriaId: 1, subcategoriaId: 8 },
      { categoriaId: 1, subcategoriaId: 9 },
      { categoriaId: 1, subcategoriaId: 10 },
      { categoriaId: 1, subcategoriaId: 11 },
      { categoriaId: 1, subcategoriaId: 12 },
      { categoriaId: 1, subcategoriaId: 13 },
      { categoriaId: 1, subcategoriaId: 14 },
      { categoriaId: 1, subcategoriaId: 15 },
      { categoriaId: 1, subcategoriaId: 16 },
      { categoriaId: 1, subcategoriaId: 17 },
      { categoriaId: 1, subcategoriaId: 18 },
      { categoriaId: 1, subcategoriaId: 19 },
      { categoriaId: 1, subcategoriaId: 20 },
      { categoriaId: 1, subcategoriaId: 21 },
      { categoriaId: 1, subcategoriaId: 22 },
      { categoriaId: 1, subcategoriaId: 23 },
      { categoriaId: 1, subcategoriaId: 24 },
      { categoriaId: 1, subcategoriaId: 25 },
      { categoriaId: 1, subcategoriaId: 26 },
      { categoriaId: 1, subcategoriaId: 27 },
      { categoriaId: 1, subcategoriaId: 28 },
      { categoriaId: 1, subcategoriaId: 29 },
      { categoriaId: 1, subcategoriaId: 30 },
      { categoriaId: 1, subcategoriaId: 31 },
      { categoriaId: 1, subcategoriaId: 32 },
      { categoriaId: 1, subcategoriaId: 33 },
      { categoriaId: 1, subcategoriaId: 34 },
      { categoriaId: 1, subcategoriaId: 35 },
      { categoriaId: 1, subcategoriaId: 36 },
      { categoriaId: 1, subcategoriaId: 37 },
      { categoriaId: 1, subcategoriaId: 38 },
      { categoriaId: 1, subcategoriaId: 39 },
      { categoriaId: 1, subcategoriaId: 40 },
      { categoriaId: 1, subcategoriaId: 41 },
      { categoriaId: 1, subcategoriaId: 42 },
      { categoriaId: 1, subcategoriaId: 43 },
      { categoriaId: 1, subcategoriaId: 44 },
      { categoriaId: 1, subcategoriaId: 45 },
      { categoriaId: 1, subcategoriaId: 46 },
      { categoriaId: 1, subcategoriaId: 47 },
      { categoriaId: 1, subcategoriaId: 48 },
      { categoriaId: 1, subcategoriaId: 49 },
      { categoriaId: 1, subcategoriaId: 50 },
      { categoriaId: 1, subcategoriaId: 51 },
      { categoriaId: 1, subcategoriaId: 52 },
      { categoriaId: 1, subcategoriaId: 53 },
      { categoriaId: 1, subcategoriaId: 54 },
      { categoriaId: 1, subcategoriaId: 55 },
      { categoriaId: 1, subcategoriaId: 56 },
      { categoriaId: 1, subcategoriaId: 57 },
      { categoriaId: 1, subcategoriaId: 58 },
      { categoriaId: 2, subcategoriaId: 18 },
      { categoriaId: 2, subcategoriaId: 21 },
      { categoriaId: 2, subcategoriaId: 33 },
      { categoriaId: 2, subcategoriaId: 34 },
      { categoriaId: 2, subcategoriaId: 35 },
      { categoriaId: 2, subcategoriaId: 37 },
      { categoriaId: 2, subcategoriaId: 41 },
      { categoriaId: 2, subcategoriaId: 59 },
      { categoriaId: 2, subcategoriaId: 60 },
      { categoriaId: 2, subcategoriaId: 61 },
      { categoriaId: 2, subcategoriaId: 62 },
      { categoriaId: 2, subcategoriaId: 63 },
      { categoriaId: 2, subcategoriaId: 64 },
      { categoriaId: 2, subcategoriaId: 65 },
      { categoriaId: 3, subcategoriaId: 8 },
      { categoriaId: 3, subcategoriaId: 9 },
      { categoriaId: 3, subcategoriaId: 10 },
      { categoriaId: 3, subcategoriaId: 11 },
      { categoriaId: 3, subcategoriaId: 12 },
      { categoriaId: 3, subcategoriaId: 13 },
      { categoriaId: 3, subcategoriaId: 14 },
      { categoriaId: 3, subcategoriaId: 55 },
      { categoriaId: 3, subcategoriaId: 66 },
      { categoriaId: 3, subcategoriaId: 67 },
      { categoriaId: 3, subcategoriaId: 68 },
      { categoriaId: 3, subcategoriaId: 69 },
      { categoriaId: 3, subcategoriaId: 70 },
      { categoriaId: 3, subcategoriaId: 71 },
      { categoriaId: 3, subcategoriaId: 72 },
      { categoriaId: 3, subcategoriaId: 73 },
      { categoriaId: 3, subcategoriaId: 74 },
      { categoriaId: 3, subcategoriaId: 75 },
      { categoriaId: 3, subcategoriaId: 91 },
      { categoriaId: 4, subcategoriaId: 8 },
      { categoriaId: 4, subcategoriaId: 9 },
      { categoriaId: 4, subcategoriaId: 10 },
      { categoriaId: 4, subcategoriaId: 11 },
      { categoriaId: 4, subcategoriaId: 12 },
      { categoriaId: 4, subcategoriaId: 13 },
      { categoriaId: 4, subcategoriaId: 14 },
      { categoriaId: 4, subcategoriaId: 16 },
      { categoriaId: 4, subcategoriaId: 17 },
      { categoriaId: 4, subcategoriaId: 21 },
      { categoriaId: 4, subcategoriaId: 53 },
      { categoriaId: 4, subcategoriaId: 55 },
      { categoriaId: 4, subcategoriaId: 76 },
      { categoriaId: 4, subcategoriaId: 77 },
      { categoriaId: 4, subcategoriaId: 78 },
      { categoriaId: 4, subcategoriaId: 79 },
      { categoriaId: 4, subcategoriaId: 80 },
      { categoriaId: 4, subcategoriaId: 81 },
      { categoriaId: 4, subcategoriaId: 82 },
      { categoriaId: 4, subcategoriaId: 83 },
      { categoriaId: 4, subcategoriaId: 84 },
      { categoriaId: 4, subcategoriaId: 85 },
      { categoriaId: 4, subcategoriaId: 86 },
      { categoriaId: 4, subcategoriaId: 87 },
      { categoriaId: 4, subcategoriaId: 92 },
      { categoriaId: 5, subcategoriaId: 1 },
      { categoriaId: 5, subcategoriaId: 23 },
      { categoriaId: 5, subcategoriaId: 24 },
      { categoriaId: 5, subcategoriaId: 25 },
      { categoriaId: 5, subcategoriaId: 26 },
      { categoriaId: 5, subcategoriaId: 27 },
      { categoriaId: 5, subcategoriaId: 28 },
      { categoriaId: 5, subcategoriaId: 29 },
      { categoriaId: 5, subcategoriaId: 30 },
      { categoriaId: 5, subcategoriaId: 31 },
      { categoriaId: 5, subcategoriaId: 32 },
      { categoriaId: 5, subcategoriaId: 33 },
      { categoriaId: 5, subcategoriaId: 34 },
      { categoriaId: 5, subcategoriaId: 35 },
      { categoriaId: 5, subcategoriaId: 36 },
      { categoriaId: 5, subcategoriaId: 37 },
      { categoriaId: 5, subcategoriaId: 38 },
      { categoriaId: 5, subcategoriaId: 39 },
      { categoriaId: 5, subcategoriaId: 40 },
      { categoriaId: 5, subcategoriaId: 41 },
      { categoriaId: 5, subcategoriaId: 42 },
      { categoriaId: 5, subcategoriaId: 43 },
      { categoriaId: 5, subcategoriaId: 44 },
      { categoriaId: 5, subcategoriaId: 45 },
      { categoriaId: 5, subcategoriaId: 46 },
      { categoriaId: 5, subcategoriaId: 47 },
      { categoriaId: 5, subcategoriaId: 48 },
      { categoriaId: 5, subcategoriaId: 49 },
      { categoriaId: 5, subcategoriaId: 50 },
      { categoriaId: 5, subcategoriaId: 51 },
      { categoriaId: 5, subcategoriaId: 52 },
      { categoriaId: 5, subcategoriaId: 55 },
      { categoriaId: 5, subcategoriaId: 61 },
      { categoriaId: 5, subcategoriaId: 78 },
      { categoriaId: 5, subcategoriaId: 88 },
      { categoriaId: 5, subcategoriaId: 89 },
      { categoriaId: 5, subcategoriaId: 90 },
      { categoriaId: 5, subcategoriaId: 93 },
      { categoriaId: 5, subcategoriaId: 94 },
      { categoriaId: 5, subcategoriaId: 95 },
      { categoriaId: 5, subcategoriaId: 96 },
      { categoriaId: 5, subcategoriaId: 97 },
      { categoriaId: 5, subcategoriaId: 98 },
      { categoriaId: 7, subcategoriaId: 2 },
      { categoriaId: 7, subcategoriaId: 99 },
      { categoriaId: 7, subcategoriaId: 100 },
      { categoriaId: 7, subcategoriaId: 101 },
      { categoriaId: 7, subcategoriaId: 102 },
      { categoriaId: 7, subcategoriaId: 103 },
      { categoriaId: 7, subcategoriaId: 104 },
      { categoriaId: 7, subcategoriaId: 105 },
      { categoriaId: 7, subcategoriaId: 106 },
      { categoriaId: 7, subcategoriaId: 107 },
      { categoriaId: 8, subcategoriaId: 108 },
      { categoriaId: 8, subcategoriaId: 109 },
      { categoriaId: 8, subcategoriaId: 110 },
      { categoriaId: 8, subcategoriaId: 111 },
      { categoriaId: 8, subcategoriaId: 112 },
      { categoriaId: 8, subcategoriaId: 113 },
      { categoriaId: 8, subcategoriaId: 114 },
      { categoriaId: 8, subcategoriaId: 115 },
      { categoriaId: 8, subcategoriaId: 116 },
      { categoriaId: 8, subcategoriaId: 117 },
      { categoriaId: 8, subcategoriaId: 118 },
      { categoriaId: 8, subcategoriaId: 119 },
      { categoriaId: 8, subcategoriaId: 120 },
      { categoriaId: 9, subcategoriaId: 121 },
      { categoriaId: 9, subcategoriaId: 122 },
      { categoriaId: 9, subcategoriaId: 123 },
      { categoriaId: 9, subcategoriaId: 124 },
      { categoriaId: 9, subcategoriaId: 125 },
      { categoriaId: 9, subcategoriaId: 126 },
      { categoriaId: 10, subcategoriaId: 127 },
      { categoriaId: 10, subcategoriaId: 128 },
      { categoriaId: 12, subcategoriaId: 129 },
      { categoriaId: 12, subcategoriaId: 130 },
      { categoriaId: 12, subcategoriaId: 131 },
      { categoriaId: 12, subcategoriaId: 132 },
      { categoriaId: 12, subcategoriaId: 133 },
      { categoriaId: 12, subcategoriaId: 134 },
      { categoriaId: 12, subcategoriaId: 135 },
      { categoriaId: 12, subcategoriaId: 136 },
      { categoriaId: 12, subcategoriaId: 137 },
      { categoriaId: 12, subcategoriaId: 138 },
      { categoriaId: 12, subcategoriaId: 139 },
      { categoriaId: 12, subcategoriaId: 140 },
      { categoriaId: 12, subcategoriaId: 141 },
      { categoriaId: 12, subcategoriaId: 142 },
    ],
  });

  console.log(`Seeding finished.`);
}

main()
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
